services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: false
      ELASTIC_PASSWORD: ""
    command: /usr/local/bin/docker-entrypoint.sh
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    labels:
      - "name=payload-cms"

volumes:
  elasticsearch_data:
    driver: local
    labels:
      - "name=payload-cms"
